name: moralpain
description: A new Flutter project.
version: 0.0.1+1
publish_to: none

environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: '^2.5.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^7.2.0
  expandable_text: 2.2.0
  flutter_bloc: ^7.2.0
  logging: ^1.0.2
  url_launcher: ^6.0.12
  uuid: 3.0.5
  moralpainapi:
    path: ../api/


dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.0
  integration_test:
    sdk: flutter
  # Preprocessing.
  flutter_launcher_icons: "^0.9.2"
  flutter_native_splash: ^1.3.1



  # This package generates native code to customize Flutter's default white native splash screen
  # with background color and splash image.
  # Customize the parameters below, and run the following command in the terminal:
  # flutter pub run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # flutter pub run flutter_native_splash:remove
flutter_native_splash:
  android: true
  ios: true
  web: true

  color: "#232D4B"
  image: assets/icons/icon.png

  android_gravity: center
  ios_content_mode: center
  web_image_mode: center

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"


flutter:
  uses-material-design: true
  assets:
    - ../resources/questionnaire.json
  fonts:
    - family: LibreFranklin
      fonts:
      - asset: fonts/LibreFranklin-Regular.ttf
      - asset: fonts/LibreFranklin-Bold.ttf
        weight: 700
      - asset: fonts/LibreFranklin-Italic.ttf
        style: italic
