# Set a default password as an environment variable before creating
# the stack. This pattern prevents us from checking in default
# passwords to the repo.

template_path: iam_user.template
parameters:
  UserName: ksullivan
  DefaultPassword: !environment_variable DEFAULT_IAM_PASSWORD
  ManagedPolicyArns:
    - arn:aws:iam::aws:policy/AdministratorAccess
