name: Publish docs to S3.

on:
  push:
    branches: 
        - main
        - repo_cleanup

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    name: Upload to S3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-oidc-provider-${{ github.repository_owner }}-moralpain_dev
          aws-region: us-east-1
      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"
      - name: redoc-cli 
        uses: seeebiii/redoc-cli-github-action@v9
        with:
          args: >
            build ${GITHUB_WORKSPACE}/infrastructure/sam/api.yaml 
            --options ${GITHUB_WORKSPACE}/docs/source/docs/backend/api/redoc.json
            --output ${GITHUB_WORKSPACE}/docs/build/html/docs/backend/api/index.html
      - name: Copy files to the test website with the AWS CLI
        run: |
          aws s3 cp --recursive ${GITHUB_WORKSPACE}/docs/build/html  s3://moralpain-site/docs/
